use std::collections::HashMap;

/// Represents an action derived from the natural language input.
#[derive(Debug, Clone)]
pub enum Action {
    ButtonClick { label: String },
    ButtonDoubleClick { label: String },
    EditEnterText { label: String, text: String },
    EditSelectText { label: String, start: Option<u32>, end: Option<u32> },
    EditCopyText { label: String },
    EditCutText { label: String },
    EditClearField { label: String },
    EditDeleteText { label: String },
    EditPasteText { label: String, text: Option<String> },
    StaticGetText { label: String },
    SetText { label: String, text: String },
    SetFocus { label: String },
    CheckboxSetState { label: String, state: bool },
    RadioSelect { label: String, variant: Option<String> },
    TreeViewSelect { label: String, node: Option<String> },
    TreeViewExpand { label: String, node: Option<String> },
    ListViewSelectItem { label: String, item: String },
    TabControlSelectTab { label: String, tab: String },
    WindowResize { width: u32, height: u32 },
    WindowMinimize { label: String },
    WindowMaximize { label: String },
    WindowClose { label: String },
    WindowMove { label: String, x: u32, y: u32 },
    LaunchApplication { app: String },
    FocusApplication { app: String },
    GroupWindows { group: String, windows: String },
    LaunchObject { object: String },
    FocusObject { object: String },
    WindowMinimizeAll,
    WindowMaximizeAll,
    WindowCloseAll,
    OpenFileProperties { file: String },
    ListSelect { label: String, item: String },
    KeyPress { key: String },
    Scroll { direction: String, amount: Option<u32> },
    Screenshot,
    SpinnerAdjust { label: String, operation: String, value: u32 },
    SelectFiles { criteria: String },
    FileOperation { operation: String },
    PasteFiles { destination: String },
    CreateDirectory { name: String },
    DeleteDirectory { name: String },
    CreateFile { name: String },
    DeleteFile { name: String },
    MultiStep { steps: Vec<Action> },
    Unknown { hint: String },
}
